@baseURL = http://localhost:8080/api/v1
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzAzNjc1MzM2fQ.JRujVMwGP7-L7DgXprIX9sp7yv8pb1fupSvkGiBFIf4
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzAzNzE1MTY3fQ.wJ39_rjWRzxPQC92uvQcHrH08BbUGxp5Xc30tda2_q4

### Register
POST {{baseURL}}/auth/register
Content-Type: application/json

{
    "username": "hendri",
    "password": "hendri",
    "email": "hendri@email.com"
}

### Login
POST {{baseURL}}/auth/login
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "test"
}

### Logout
GET {{baseURL}}/auth/logout
Authorization: {{adminToken}}

### Get users by role user
GET {{baseURL}}/users
Authorization: {{userToken}}

### Get users by rolde admin
GET {{baseURL}}/users
Authorization: {{adminToken}}

### Get user by admin token
GET {{baseURL}}/users/3
Authorization: {{adminToken}}

### Get user by user token
GET {{baseURL}}/users/3
Authorization: {{userToken}}

### Delete user
DELETE {{baseURL}}/users/15
Authorization: {{adminToken}}

### Update user
PUT {{baseURL}}/users/14
Content-Type: application/json
Authorization: {{adminToken}}

{
    "username": "hendri",
    "password": "hendri",
    "email": "hendri@email.com",
    "role_id": 1
}

### Update profile
PUT {{baseURL}}/me
Content-Type: application/json
Authorization: {{adminToken}}

{
    "username": "admin",
    "password": "admin",
    "email": "test@email.com"
}

### Get books
GET {{baseURL}}/books
Authorization: {{userToken}}

### Get book
GET {{baseURL}}/books/100
Authorization: {{userToken}}

### Create book
POST {{baseURL}}/books
Content-Type: application/json
Authorization: {{adminToken}}

{
    "title": "Book 1",
    "author": "Author 1",
    "description": "Description 1",
    "image": "Image 1"
}

### Create book user token
POST {{baseURL}}/books
Content-Type: application/json
Authorization: {{userToken}}

{
    "title": "Book 1",
    "author": "Author 1",
    "description": "Description 1",
    "image": "Image 1"
}

### Update book
PUT {{baseURL}}/books/7
Content-Type: application/json
Authorization: {{adminToken}}

{
    "title": "Book Updated 1",
    "author": "Author Updated 1",
    "description": "Description Updated 1",
    "image": "Image Updated 1"
}

### Update book user token
PUT {{baseURL}}/books/7
Content-Type: application/json
Authorization: {{userToken}}

{
    "title": "Book Updated 1",
    "author": "Author Updated 1",
    "description": "Description Updated 1",
    "image": "Image Updated 1"
}

### Delete book
DELETE {{baseURL}}/books/7
Authorization: {{adminToken}}

### Delete book user token
DELETE {{baseURL}}/books/7
Authorization: {{userToken}}